name: CI

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
            ref: Test
        
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
            version: latest
            platform: x64

      - name: Compile
        working-directory: ./src
        run: |
            gcc -s -fPIC -shared -o prelibsynophoto.so prelibsynophoto.c
            gcc -s -fPIC -shared -o prelibsynosdk.so prelibsynosdk.c
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PreloadLibrary
          path: src/*.so
          if-no-files-found: error        
              
      - name: Delete old workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
